### ISSUE TITLE
Another biome conflict :(

### ISSUE THREAD

**Issue by Dumpling00** [InvictusSlayer/Slayers-Beasts#6]
Hey again. We'll get it one of these day!!

Just got another crash (witht he newest version of Slayer's), this time with Worldgen mod Nature's Spirit. Specifically it seems the conflict seems to be with  biome / natures_spirit:arid_savanna and biome / slayersbeasts:rocky_brushland.

These crashes happen when I happen to spawn in or near one of these conflicting biomes, so it might take a while to make sure all the kinks are worked out. Not sure it if could be an idea to have the mod run a check as the game launches (instead of crashing after or mid-world generation) so we can potentially get the whole list of conflicts in one swoop.

**Comment by InvictusSlayer** [comment]
Okay this was a more confusing one since it involved natures_spirit:chaparral as well but it should be sorted now. As for running a check I'm not sure because I think it would take longer to actually write something that checks that than it would be to brute force it, seeing as once the biomes are integrated correctly, they will work until there is some change. 

Thanks so much for your help and patience with this!! It's a massive help as most people would just leave out the mod and not bother getting in contact.

**Comment by Dumpling00** [comment]
No problem! You've been amazing at this, I can't wait to see what else you add to this mod! Personally I love every mod that adds biomes and mobs, so it was love at first sight with yours.

Keep rocking! I'll wait for the fix and run another test again!
